version: '3.8'
services:
  flowise:
    image: flowiseai/flowise
    ports:
      - "3000:3000"
    volumes:
      - ./.flowise:/root/.flowise
    environment:
      - FLOWISE_API_KEY=${FLOWISE_API_KEY}
      - FLOWISE_CHATFLOW_ID=${FLOWISE_CHATFLOW_ID}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - SERP_API_KEY=${SERP_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/v1/chatflows"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata: 