#!/usr/bin/env python3
"""
Fix Cursor rule frontmatter in-place (best-effort).
- Creates frontmatter if missing
- Fills required keys if absent, preserving existing values
- Computes checksum of body
Defaults:
- RULE_PHASE env var may override 'phase' (default: 9.5.7.4.6)
- OWNER env var may override 'owner' (default: researcher-ssot)
"""
from __future__ import annotations
import datetime as dt, hashlib, json, os, re, sys
from pathlib import Path
try:
    import yaml
except Exception:
    print(json.dumps({"status":"error","error":{"code":"pyyaml_missing","message":"PyYAML is required: pip install pyyaml"}}))
    sys.exit(1)

ROOT = Path(".").resolve()
RULES_DIR = ROOT/".cursor"/"rules"
TODAY = dt.date.today().isoformat()
DEFAULT_PHASE = os.environ.get("RULE_PHASE","9.5.7.4.6")
DEFAULT_OWNER = os.environ.get("OWNER","researcher-ssot")

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n(.*)\Z", re.DOTALL)

def sha256_text(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()

def parse(path: Path):
    txt = path.read_text(encoding="utf-8", errors="ignore")
    m = FM_RE.match(txt)
    if not m:
        return {}, txt
    try:
        fm = yaml.safe_load(m.group(1)) or {}
        if not isinstance(fm, dict):
            fm = {}
    except Exception:
        fm = {}
    return fm, m.group(2)

def build_frontmatter(existing: dict, rule_id: str, body: str, is_global: bool):
    fm = dict(existing) if isinstance(existing, dict) else {}
    # Required defaults (preserve existing)
    fm.setdefault("description", f"{rule_id.replace('_', ' ').title()} rule for Living Truth Engine")
    fm.setdefault("alwaysApply", is_global)
    fm.setdefault("rule_id", rule_id)
    fm.setdefault("title", f"Cursor Rule: {rule_id}")
    fm.setdefault("phase", DEFAULT_PHASE)
    fm.setdefault("applies", "always" if is_global else "phase")
    fm.setdefault("enforcement", "strict" if is_global else "advisory")
    fm.setdefault("owner", DEFAULT_OWNER)
    fm.setdefault("updated", TODAY)
    fm.setdefault("version", 1)
    fm.setdefault("scope", "all" if is_global else ["**/*"])
    fm.setdefault("summary", "Rule autogenerated/normalized by SSOT fixer; please refine summary.")
    fm.setdefault("links", [])
    # checksum of body (content after frontmatter)
    fm["checksum"] = sha256_text(body or "")
    return fm

def write_rule(path: Path, fm: dict, body: str):
    import yaml
    new = "---\n" + yaml.safe_dump(fm, sort_keys=False).strip() + "\n---\n" + (body or "")
    path.write_text(new, encoding="utf-8")

def main():
    fixed = []
    if not RULES_DIR.exists():
        print(json.dumps({"status":"ok","data":{"fixed":0,"note":"no .cursor/rules found"}}))
        return
    for p in sorted(RULES_DIR.glob("*.mdc")):
        rule_id = p.stem
        is_global = (p.name == "00-global.mdc")
        existing, body = parse(p)
        fm = build_frontmatter(existing, rule_id, body, is_global)
        write_rule(p, fm, body)
        fixed.append(p.name)
    print(json.dumps({"status":"ok","data":{"fixed":len(fixed),"files":fixed}}))

if __name__ == "__main__":
    main()
